name: letsgohikeenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - matplotlib
  - pandas
  - numpy
  - pylint
  - streamlit
  - folium
  - streamlit-folium
  - geopy
  - pip:
      - python-weather
      -google.generativeai as genai

